routes/web.php
<?php

use App\Http\Controllers\AnswerController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ForumController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\ProfilController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
*/



Route::get('/', [LoginController::class, 'login']);
Route::post('/', [LoginController::class, 'auth']);
Route::post('/logout', [LoginController::class, 'logout']);
Route::get('/register', [RegisterController::class, 'register']);
Route::post('/register', [RegisterController::class, 'store']);

//proofile
Route::get('/profile', [ProfilController::class, 'profile']);
Route::GET('/add-profile', [ProfilController::class, 'create']);
Route::POST('/add-profile', [ProfilController::class, 'store']);
Route::get("/edit-profile/{id}", [ProfilController::class, 'editprofile']);
Route::post('/edit-profile/{id}', [ProfilController::class, 'editing']);

// CRUD Forum
Route::resource('/forum', ForumController::class);
Route::get('/forum/{id}', [ForumController::class, 'show']);
// CRUD Forum_Category
Route::resource('/category', CategoryController::class);

Route::post('/answer/{id}', [AnswerController::class, 'store']);

app/Models/Forum.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Forum extends Model
{
    use HasFactory;
    protected $table = 'forums';
    protected $guarded = [];

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }

    // public function answer()
    // {
    //     return $this->morphMany(User::class, 'answer');
    // }
    public function answer()
    {
        return $this->hasMany(Answer::class, 'question_id');
    }
}

app/Http/Controllers/ForumController.php
<?php

namespace App\Http\Controllers;

use App\Models\Answer;
use App\Models\Category;
use App\Models\Forum;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;


class ForumController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $forum = Forum::get();
        return view('halaman.forum.index', ['forum' => $forum]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $forum = Forum::get();
        return view('halaman.forum.tambah', [
            'forum' => $forum,
            'categories' => Category::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'question' => 'required|max:255',
            'category_id' => 'required',
            'description' => 'required',
            'image' => 'image|file|max:1024'
        ]);
        if ($request->file('image')) {
            $validatedData = $request->file('image')->store('quest-images');
        }
        $forum = new Forum;
        $forum->question = $request->question;
        $forum->description = $request->description;
        $forum->image = $request->image ? $validatedData : null;
        $forum->category_id = $request->category_id;
        $forum->user_id = $request->user_id = auth()->user()->id;
        $forum->save();
        return redirect('/forum');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Forum  $forum
     * @return \Illuminate\Http\Response
     */
    public function show(Forum $forum)
    {
        $forum = Forum::find($forum);
        return view('halaman.forum.detail', ['forums' => $forum]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Forum  $forum
     * @return \Illuminate\Http\Response
     */
    public function edit(Forum $forum)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Forum  $forum
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Forum $forum)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Forum  $forum
     * @return \Illuminate\Http\Response
     */
    public function destroy(Forum $forum)
    {
        //
    }
}

resources/views/halaman/forum/detail.blade.php
@extends('layouts.main')
@section('title')
Halaman Forum
@endsection
@section('content')
<div class="container">
     <div class="row">
          <div class="col-2 my-5">
               <ul class="nav nav-tabs d-block">
                    <li class="nav-item">
                         <a class="nav-link active" aria-current="page" href="/forum">Forum</a>
                    </li>
                    <li class="nav-item">
                         <a class="nav-link" href="/category">Tags</a>
                    </li>
                    <li class="nav-item">
                         <a class="nav-link" href="#">profile</a>
                    </li>
               </ul>
          </div>
          <div class="col-8 my-5">
               @foreach ($forums as $item)
               <div class="my-5">
                    <div class="media-body">
                         <h3 class="text-start">{{ $item->question }}</h3>
                    </div>
                    <div class="card mb-3">
                         <div class="card-body">
                              <p class="card-text">{!! $item->description !!}</p>

                         </div>
                         @if ($item->image)
                         <img src="{{ asset('storage/' . $item->image) }}" class="img-fluid">
                    </div>
                    @else

                    @endif
               </div>

               <hr>
               <h5>Bantu Jawab</h5>
               @foreach ($forums as $item)
               @foreach ($item->answer->where('question_id', $item->id) as $data)
               <div class="card mb-3">
                  <div class="card">
                      <h5 class="card-title mx-2">{{ $data->username }}</h5>
                      <p class="card-text mx-3">{{ $data->answer_text }}</p>
                         <div class="my-2">
                              <p class="card-text text-end"><small class="text-muted">Created at {{ $item->created_at }} </small></p>
                              <img src="https://adminlte.io/themes/v3/dist/img/AdminLTELogo.png" width="30" height="30" class="rounded-circle border float-end mx-2">
                              <p class="card-text text-end"><a class="text-decoration-none" href="#">{{ auth()->user()->username}}</a></p>
                         </div>
                    </div>
                  </div>
               @endforeach
               @endforeach

               <hr>

               <form action="/answer/{{ $item->id }}" method="post">
                    @method('post')
                    @csrf
                    <div class="form-floating">
                         <textarea class="form-control" name="answer_text" placeholder="Leave a comment here" id="floatingTextarea2" style="height: 100px"></textarea>
                         <label for="floatingTextarea2">Bantu Jawab</label>
                         <button type="submit" class="btn btn-primary btn-sm my-4">Primary</button>
                    </div>
               </form>

               @endforeach
          </div>

     </div>
</div>
</div>
@endsection

resources/views/halaman/forum/index.blade.php
@extends('layouts.main')
@section('title')
Halaman Forum
@endsection
@push('script')
<script>
     Swal.fire(
          'Good job!',
          'You clicked the button!',
          'success'
     )
</script>
@endpush
@section('content')
<div class="container">
     <div class="row">
          <div class="col-2 my-5">
               <ul class="nav nav-tabs d-block">
                    <li class="nav-item">
                         <a class="nav-link active" aria-current="page" href="/forum">Forum</a>
                    </li>
                    <li class="nav-item">
                         <a class="nav-link" href="/category">Tags</a>
                    </li>
                    <li class="nav-item">
                         <a class="nav-link" href="/profile">profile</a>
                    </li>
               </ul>
          </div>
          <div class="col-8 my-5">
               @auth
               <a class="btn btn-warning bg-gradient mb-2 float-end fw-bold font-monospace" href="/forum/create"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill me-3" viewBox="0 0 16 16">
                         <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z" />
                    </svg>Buat Pertanyaan</a>
               @else
               <a class="btn btn-warning bg-gradient mb-2 float-end fw-bold font-monospace" href="/"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill me-3" viewBox="0 0 16 16">
                         <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z" />
                    </svg>Buat Pertanyaan</a> @endauth
               <h1 class="mb-2">OutofStack</h1>
               <p class="fs-5 mb-4">Tempat Berkomunikasi dengan cara mengajukan pertanyaan atau menjawab sebuah pertanyaan.</p>
               <hr class="mb-5">
               @foreach ($forum as $item)
               <div class="card shadow rounded my-4">
                    <div class="card-body">
                         <h4 class="card-title my-4">{{ $item->question }}</h4>
                         <p class="card-text my-3">{!! $item->description !!}
                              <a href="/forum/{{$item->id}}" class="align-center badge bg-light text-dark bg-gradient shadow-sm rounded">Readmore...</a>
                         </p>

                         <h5>
                              <a href="/category/{{$item->category->id}}"><span class="badge bg-info shadow bg-gradient">{{ $item->category->name }}</span></a>
                         </h5>
                         <div class="my-2">
                              <p class="card-text text-end"><small class="text-muted">Created at {{ $item->created_at }} </small></p>
                              <img src="https://adminlte.io/themes/v3/dist/img/AdminLTELogo.png" width="30" height="30" class="rounded-circle border float-end mx-2">
                              @auth
                                  <p class="card-text text-end"><a class="text-decoration-none" href="#">{{ auth()->user()->username}}</a></p>
                              @endauth
                              
                         </div>
                    </div>

               </div>
               @endforeach
          </div>
          <div class="col-2 my-5">
               <div class="card" style="width: 10rem;">
                    <div class="card-body shadow rounded">
                         <h5 class="card-title">Selamat Datang di OutofStack</h5>
                         <hr>
                         <p class="card-text">Mulailah berinteraksi dengan bahasa yang sopan dan ramah</p>
                    </div>
               </div>
          </div>
     </div>
</div>
@endsection

resources/views/halaman/forum/tambah.blade.php
@extends('layouts.main')
@push('style')
<link rel="stylesheet" type="text/css" href="https://unpkg.com/trix@2.0.0/dist/trix.css">
<style>
     trix-toolbar [data-trix-button-group="file-tools"] {
          display: none;
     }
</style>
@endpush
@push('script')
<script type="text/javascript" src="https://unpkg.com/trix@2.0.0/dist/trix.umd.min.js"></script>
<script>
     document.addEventListener('trix-file-accept', function(e) {
          e.preventDefault();
     })
</script>
@endpush
@section('content')
<div class="container">
     <h3 class="my-5">Buat Pertanyaan Kepada Publik</h3>
     <div class="my-4">
          <form action="{{ route('forum.store') }}" method="POST" enctype="multipart/form-data">
               @csrf
               <div class="form-group">
                    <label class="mb-2" for="question">Pertanyaan</label>
                    <input type="text" name="question" value="{{ old('question') }}" class="form-control @error('question') is-invalid @enderror">
                    @error('question')
                    <div class="invalid-feedback">
                         {{ $message }}
                    </div>
                    @enderror
               </div>
               <div class="form-group my-3">
                    <label class="mb-2" for="description">Deskripsi</label>
                    @error('description')
                    <p class="text-danger">{{ $message }}</p>
                    @enderror
                    <input id="description" type="hidden" name="description" value="{{ old('description') }}">
                    <trix-editor input="description"></trix-editor>
               </div>
               <div class="form-group my-3">
                    <label class="mb-2" for="category">Tags</label>
                    <select class="form-select " name="category_id">
                         @foreach ($categories as $item)
                         @if (old('category_id') == $item->id)
                         <option value="{{ $item->id }}" selected>{{ $item->name }}</option>
                         @else
                         <option value="{{ $item->id }}">{{ $item->name }}</option>
                         @endif
                         @endforeach
                    </select>
               </div>
               <div class="form-group my-3">
                    <label class="mb-2" for="description">Image</label>
                    <div class="input-group mb-3">
                         <label class="input-group-text" for="inputGroupFile01">Upload</label>
                         <input type="file" name="image" class="form-control" id="inputGroupFile01">
                    </div>
               </div>
               <button type="submit" class="btn btn-primary mt-4">Submit</button>
               <a href="/post" class="btn btn-danger mt-4">Back</a>
          </form>
     </div>
</div>
@endsection